services:
  postgres:
    image: postgres:16-alpine
    container_name: parcel-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: parcel-redis
    # 开启aof模式
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  kafka:
    image: apache/kafka:3.7.0
    container_name: parcel-kafka
    ports:
      - "19092:9092"
    environment:
      # KRaft 单节点模式
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # controller 投票节点
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # 监听端口
      # PLAINTEXT: 给 app / 本机客户端连接
      # CONTROLLER: Kafka 内部 controller 通信
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      # listener 协议映射
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # 本地单节点必须设置为 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # 本地开发允许自动创建 topic
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # 减少本地 consumer group 初次等待
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 10s
      timeout: 10s
      retries: 10

    volumes:
      - kafka-data:/tmp/kraft-combined-logs

  app:
    build:
      context: .
      # 本机根据 Dockerfile 构建镜像，然后启动
      dockerfile: Dockerfile
    container_name: parcel-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        # 等 kafka 容器启动即可
        condition: service_started
    environment:
      # Spring Boot 会先加载：application.properties；再加载：application-docker.properties
      # 如果两边有同名配置，后者覆盖前者
      SPRING_PROFILES_ACTIVE: docker
      SPRING_MAIN_LOG_STARTUP_INFO: "true"
      DEBUG: "true"

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parcelhub
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_CRYPTO_PASSWORD: ${APP_CRYPTO_PASSWORD}
      APP_CRYPTO_SALT: ${APP_CRYPTO_SALT}

      JAVA_OPTS: "-Xms256m -Xmx512m"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/8080'"]
      # test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: parcel-prometheus
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "9090:9090"
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.1.0
    container_name: parcel-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  redis-data:
  kafka-data:
  grafana-data: