spring.application.name=Parcel-Hub-Core
server.port=8080

# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/parcelhub
spring.datasource.username=lily
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
# =========================
# JPA
# =========================
# \u6821\u9A8C\u6570\u636E\u5E93\u7ED3\u6784\u662F\u5426\u548C JPA \u5B9E\u4F53\u5339\u914D\uFF0C\u4F46\u4E0D\u505A\u4FEE\u6539
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# =========================
# Flyway \u914D\u7F6E
# =========================
spring.flyway.enabled=true
# Flyway \u811A\u672C\u7684\u8DEF\u5F84\uFF0C\u9ED8\u8BA4\u662F db/migration
spring.flyway.locations=classpath:db/migration
# \u542F\u7528\u8FD9\u4E2A\u9009\u9879\u7528\u4E8E\u5728\u7B2C\u4E00\u6B21\u8FD0\u884C\u65F6\u4E3A\u73B0\u6709\u6570\u636E\u5E93\u5EFA\u7ACB\u57FA\u7840\u7248\u672C
spring.flyway.baseline-on-migrate=true
# \u5141\u8BB8 Flyway \u6267\u884C\u65E0\u5E8F\u7684 SQL \u811A\u672C
spring.flyway.out-of-order=true

# =========================
# redis
# =========================
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.ssl.enabled=false
# redis distributedLock prefix
app.distributed-lock.prefix=lock:parcel:op:

# =========================
# kafka
# =========================
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# \u751F\u4EA7\u8005\u6D88\u606F\u5E42\u7B49
spring.kafka.producer.properties.enable.idempotence=true
# acks=all\u3001retries>0\uFF0C\u4E14 max.in.flight.requests.per.connection <= 5 \u5E42\u7B49\u624D\u4F1A\u751F\u6548
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
# \u751F\u4EA7\u8005\u5728\u53D1\u9001\u6279\u91CF\u6D88\u606F\u4E4B\u524D\u7B49\u5F85\u66F4\u591A\u6D88\u606F\u52A0\u5165\u8BE5\u6279\u6B21\u7684\u6700\u957F\u65F6\u95F4
spring.kafka.producer.properties.linger.ms=5
# \u6D88\u8D39\u7EC4
spring.kafka.consumer.group-id=parcel-default-group
# \u4E0D\u81EA\u52A8\u63D0\u4EA4offset
spring.kafka.consumer.enable-auto-commit=false
# \u5982\u679C\u670D\u52A1\u7AEF\u7684offset\u4E22\u4E86\uFF0C\u81EA\u52A8\u4ECE\u6700\u65E9\u7684\u6D88\u606F\u5F00\u59CB\u6D88\u8D39
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.isolation.level=read_committed
# \u6D88\u8D39\u8005\u6BCF\u5904\u7406\u5B8C\u4E00\u6761\u6D88\u606F\uFF0C\u7ACB\u5373\u5411 Kafka \u63D0\u4EA4\u6D88\u8D39\u504F\u79FB\u91CF
spring.kafka.listener.ack-mode=record
# \u5355\u5B9E\u4F8B\u4E2D\u6D88\u606F\u76D1\u542C\u5BB9\u5668\u7684\u5E76\u53D1\u7EBF\u7A0B\u6570\uFF1A\u591A\u7EBF\u7A0B\u5904\u7406\u6D88\u606F
spring.kafka.listener.concurrency=3

# =========================
# app
# =========================
app.outbox.batch-size=50
app.outbox.fixed-delay-ms=5000
app.outbox.max-retry=20
app.outbox.retry-base-seconds=10
app.outbox.recovery-s=300
app.outbox.timeout-s=300
#  \u6D88\u8D39\u8005
app.consumer.group.parcel-sms=parcel-sms-consumer
app.consumer.group.parcel-app=parcel-app-consumer

# =========================
# log
# =========================
# \u628A\u63A7\u5236\u53F0\u65E5\u5FD7\u8F93\u51FA\u6210 JSON \u7ED3\u6784\u5316\u683C\u5F0F
# logging.structured.format.console=logstash
# \u628A MDC\u91CC\u7684\u4E0A\u4E0B\u6587\u4E00\u8D77\u8F93\u51FA\u5230 JSON \u65E5\u5FD7
# logging.structured.json.context.include=true
# \u91C7\u6837\u7387\u5230100%
# management.tracing.sampling.probability=1.0

# =========================
# crypto
# =========================
app.crypto.password=HUlcGaWCfXUPbbHCs-78ObFwUCcdEy4RlobNLbOWSFc
app.crypto.salt=06d76593a6abd8015d1bb1da3777339d
jwt.secret=Z1TIi6xB1peUANzMEslwn1E+VGI8TVOyXat8phJW6BQ=

# =========================
# springdoc
# =========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs

# =========================
# endpoint + metrics
# =========================
# \u66B4\u9732\u54EA\u4E9B actuator endpoint \u7ED9 HTTP \u8BBF\u95EE
management.endpoints.web.exposure.include=health,info,metrics,prometheus
# \u5F00\u542F liveness/readiness \u63A2\u9488\uFF0C\u9002\u5408 Docker/K8s/\u90E8\u7F72\u5E73\u53F0
management.endpoint.health.probes.enabled=true
# \u5F00\u542F Prometheus \u6307\u6807\u5BFC\u51FA
management.prometheus.metrics.export.enabled=true
# health endpoint \u663E\u793A\u7EC6\u8282\u7B56\u7565
management.endpoint.health.show-details=when_authorized
# info endpoint \u53EF\u4EE5\u663E\u793A\u5E94\u7528\u57FA\u7840\u4FE1\u606F
management.info.env.enabled=true
# \u81EA\u5B9A\u4E49 info \u5185\u5BB9
info.app.name=${spring.application.name}
info.app.description=Parcel Hub Core Backend Service
info.app.version=0.1.0
