spring.application.name=Parcel-Hub-Core
# =========================
# redis
# =========================
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.ssl.enabled=false
# redis distributedLock prefix
app.distributed-lock.prefix=lock:parcel:op:
# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/parcel
spring.datasource.username=lily
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false
# =========================
# kafka - local
# =========================
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# \u751F\u4EA7\u8005\u6D88\u606F\u5E42\u7B49
spring.kafka.producer.properties.enable.idempotence=true
# acks=all\u3001retries>0\uFF0C\u4E14 max.in.flight.requests.per.connection <= 5 \u5E42\u7B49\u624D\u4F1A\u751F\u6548
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
# \u751F\u4EA7\u8005\u5728\u53D1\u9001\u6279\u91CF\u6D88\u606F\u4E4B\u524D\u7B49\u5F85\u66F4\u591A\u6D88\u606F\u52A0\u5165\u8BE5\u6279\u6B21\u7684\u6700\u957F\u65F6\u95F4
spring.kafka.producer.properties.linger.ms=5
# \u6D88\u8D39\u7EC4
spring.kafka.consumer.group-id=parcel-default-group
# \u4E0D\u81EA\u52A8\u63D0\u4EA4offset todo
spring.kafka.consumer.enable-auto-commit=false
# \u5982\u679C\u670D\u52A1\u7AEF\u7684offset\u4E22\u4E86\uFF0C\u81EA\u52A8\u4ECE\u6700\u65E9\u7684\u6D88\u606F\u5F00\u59CB\u6D88\u8D39
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.isolation.level=read_committed
# \u6D88\u8D39\u8005\u6BCF\u5904\u7406\u5B8C\u4E00\u6761\u6D88\u606F\uFF0C\u7ACB\u5373\u5411 Kafka \u63D0\u4EA4\u6D88\u8D39\u504F\u79FB\u91CF
spring.kafka.listener.ack-mode=record
# \u5355\u5B9E\u4F8B\u4E2D\u6D88\u606F\u76D1\u542C\u5BB9\u5668\u7684\u5E76\u53D1\u7EBF\u7A0B\u6570\uFF1A\u5355\u7EBF\u7A0B\u987A\u5E8F\u5904\u7406\u6240\u6709\u5206\u533A\u7684\u6D88\u606F
spring.kafka.listener.concurrency=1
# =========================
# app
# =========================
app.outbox.batch-size=50
app.outbox.fixed-delay-ms=5000
app.outbox.max-retry=20
app.outbox.retry-base-seconds=10
#  \u6D88\u8D39\u8005
app.consumer.group.parcel-sms=parcel-sms-consumer
app.consumer.group.parcel-app=parcel-app-consumer