-- =====================================================
-- database：postgreSQL
-- table count：7
-- =====================================================

-- =====================================================
-- message_outbox
-- =====================================================
CREATE TABLE message_outbox
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id      varchar(64)                             NOT NULL,
    topic         varchar(128)                            NOT NULL,
    event_key     varchar(128)                            NOT NULL,
    payload       text                                    NOT NULL,
    status        varchar(32)                             NOT NULL,
    retry_count   int4        DEFAULT 0                   NOT NULL,
    last_error    varchar(500) NULL,
    next_retry_at timestamptz NULL,
    processing_at timestamptz NULL,
    created_at    timestamptz DEFAULT CURRENT_TIMESTAMP   NOT NULL,
    updated_at    timestamptz DEFAULT CURRENT_TIMESTAMP   NOT NULL,
    published_at  timestamptz NULL,
    CONSTRAINT message_outbox_pkey PRIMARY KEY (id),
    CONSTRAINT uk_message_outbox_event_id UNIQUE (event_id)
);
CREATE INDEX idx_outbox_status_next_retry ON message_outbox USING btree (status, next_retry_at);
-- Table Triggers
CREATE
OR REPLACE FUNCTION update_message_outbox_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at
= CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trigger_message_outbox_updated_at
    BEFORE UPDATE
    ON message_outbox
    FOR EACH ROW
    EXECUTE FUNCTION update_message_outbox_updated_at();

-- =====================================================
-- parcel
-- =====================================================
CREATE TABLE parcel
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    station_code         varchar(50)                                  NOT NULL,
    waybill_code         varchar(20)                                  NOT NULL,
    pickup_code          varchar(32)                                  NOT NULL,
    shelf_code           varchar(64)                                  NOT NULL,
    recipient_name       varchar(32) NULL,
    recipient_mobile     varchar(32)                                  NOT NULL,
    status               int4        DEFAULT 0                        NOT NULL,
    notify_status        int4        DEFAULT 0                        NOT NULL,
    latest_inbound_time  timestamptz                                  NOT NULL,
    latest_outbound_time timestamptz DEFAULT '9999-12-31 23:59:59+00' NOT NULL,
    created_at           timestamptz DEFAULT CURRENT_TIMESTAMP        NOT NULL,
    updated_at           timestamptz DEFAULT CURRENT_TIMESTAMP        NOT NULL,
    CONSTRAINT parcel_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_parcel_station_waybill_code ON parcel USING btree (station_code, waybill_code);
CREATE INDEX idx_parcel_station_pickup ON parcel USING btree (station_code, pickup_code);
CREATE INDEX idx_parcel_station_shelf ON parcel USING btree (station_code, shelf_code);
CREATE INDEX idx_parcel_station_status ON parcel USING btree (station_code, status);
-- Table Triggers
CREATE
OR REPLACE FUNCTION trg_parcel_before_update()
RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at
= CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER before_update_parcel
    BEFORE UPDATE
    ON parcel
    FOR EACH ROW
    EXECUTE FUNCTION trg_parcel_before_update();

-- =====================================================
-- parcel_notify_record
-- =====================================================
CREATE TABLE parcel_notify_record
(
    id            int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    station_code  varchar(50)                           NOT NULL,
    waybill_code  varchar(64)                           NOT NULL,
    channel       varchar(32)                           NOT NULL,
    notify_time   timestamptz                           NOT NULL,
    "content"     text NULL,
    operator_code varchar(50)                           NOT NULL,
    operator_name varchar(128)                          NOT NULL,
    created_at    timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    unique_id     varchar(50)                           NOT NULL,
    status        int4 NULL,
    mobile        varchar(62) NULL,
    CONSTRAINT parcel_notify_record_pkey PRIMARY KEY (id),
    CONSTRAINT parcel_notify_record_unique UNIQUE (unique_id, channel)
);
CREATE INDEX idx_parcel_notify_record_station_waybill ON parcel_notify_record USING btree (station_code, waybill_code);
-- Table Triggers
CREATE
OR REPLACE FUNCTION set_parcel_notify_record_updated_at()
RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at
= CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trg_parcel_notify_record_updated_at
    BEFORE UPDATE
    ON parcel_notify_record
    FOR EACH ROW
    EXECUTE FUNCTION set_parcel_notify_record_updated_at();

-- =====================================================
-- parcel_op_record
-- =====================================================
CREATE TABLE parcel_op_record
(
    id            int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    station_code  varchar(255)                          NOT NULL,
    waybill_code  varchar(20)                           NOT NULL,
    op_time       timestamptz                           NOT NULL,
    op_type       int4                                  NOT NULL,
    operator_code varchar(50)                           NOT NULL,
    operator_name varchar(255) NULL,
    created_at    timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    unique_id     varchar(50)                           NOT NULL,
    detail        varchar(500) NULL,
    CONSTRAINT parcel_op_record_pkey PRIMARY KEY (id),
    CONSTRAINT parcel_op_record_unique UNIQUE (unique_id)
);
CREATE INDEX idx_parcel_op_record_station_waybill ON parcel_op_record USING btree (station_code, waybill_code);
-- Table Triggers

CREATE
OR REPLACE FUNCTION set_parcel_op_record_updated_at()
RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at
= CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trg_parcel_op_record_updated_at
    BEFORE UPDATE
    ON parcel_op_record
    FOR EACH ROW
    EXECUTE FUNCTION set_parcel_op_record_updated_at();

-- =====================================================
-- station_info
-- =====================================================
CREATE TABLE station_info
(
    id                  int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                varchar(255) NULL,
    "name"              varchar(255)                          NOT NULL,
    status              int4        DEFAULT 0                 NOT NULL,
    principal           varchar(255) NULL,
    contact_mobile      varchar(255)                          NOT NULL,
    mobile_hash         varchar(255)                          NOT NULL,
    address             varchar(255) NULL,
    longitude           numeric(38, 2) NULL,
    latitude            numeric(38, 2) NULL,
    active_time         timestamptz DEFAULT '1970-01-01 08:00:00+08'::timestamp with time zone NOT NULL,
    exit_time           timestamptz DEFAULT '10000-01-01 07:59:59+08'::timestamp with time zone NOT NULL,
    business_start_time time NULL,
    business_end_time   time NULL,
    remark              text NULL,
    created_at          timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at          timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT station_info_code_key UNIQUE (code),
    CONSTRAINT station_info_mobile_key UNIQUE (mobile_hash),
    CONSTRAINT station_info_pkey PRIMARY KEY (id)
);
-- Table Triggers
CREATE
OR REPLACE FUNCTION update_station_info_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at
= CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trigger_station_info_updated_at
    BEFORE UPDATE
    ON station_info
    FOR EACH ROW
    EXECUTE FUNCTION update_station_info_updated_at();

-- =====================================================
-- user_info
-- =====================================================
CREATE TABLE user_info
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code         varchar(50) NULL,
    username     varchar(100)                          NOT NULL,
    station_code varchar(50)                           NOT NULL,
    "role"       varchar(20) DEFAULT 'STAFF'           NOT NULL,
    status       int4        DEFAULT 0                 NOT NULL,
    "password"   varchar(255)                          NOT NULL,
    created_at   timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at   timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT user_info_code_key UNIQUE (code),
    CONSTRAINT user_info_username_key UNIQUE (username),
    CONSTRAINT user_info_pkey PRIMARY KEY (id)
);
-- Table Triggers
CREATE
OR REPLACE FUNCTION update_user_info_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at
= CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trigger_user_info_updated_at
    BEFORE UPDATE
    ON user_info
    FOR EACH ROW
    EXECUTE FUNCTION update_user_info_updated_at();

-- =====================================================
-- waybill_registry
-- =====================================================
CREATE TABLE waybill_registry
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    waybill_code varchar(20)                           NOT NULL,
    station_code varchar(255)                          NOT NULL,
    status       int4        DEFAULT 0                 NOT NULL,
    created_at   timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at   timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_waybill_registry_station_code_not_blank CHECK ((char_length(btrim((station_code)::text)) > 0)),
    CONSTRAINT chk_waybill_registry_status CHECK ((status = ANY (ARRAY[0, 1, 2]))),
    CONSTRAINT chk_waybill_registry_waybill_code_not_blank CHECK ((char_length(btrim((waybill_code)::text)) > 0)),
    CONSTRAINT waybill_registry_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_waybill_code_active ON waybill_registry USING btree (waybill_code) WHERE (status = 0);
-- Table Triggers
CREATE
OR REPLACE FUNCTION trg_waybill_registry_set_updated_at()
RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at
= CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER before_update_waybill_registry
    BEFORE UPDATE
    ON waybill_registry
    FOR EACH ROW
    EXECUTE FUNCTION trg_waybill_registry_set_updated_at();
