name: Deploy to Local

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy, for example: latest or commit sha"
        required: true
        default: "latest"

permissions:
  contents: read
  # 允许读取 GitHub Container Registry 里的镜像
  packages: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        # 后面要用仓库里的compose.prod.yaml；所以把 GitHub 仓库代码拉到 runner 当前工作目录
        uses: actions/checkout@v4

      - name: Generate .env.prod
        run: |
          cat > .env.prod <<EOF
          SPRING_PROFILES_ACTIVE=prod
          POSTGRES_DB=parcelhub
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          SPRING_DATA_REDIS_HOST=redis
          SPRING_DATA_REDIS_PORT=6379
          SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
          APP_CRYPTO_PASSWORD=${{ secrets.APP_CRYPTO_PASSWORD }}
          APP_CRYPTO_SALT=${{ secrets.APP_CRYPTO_SALT }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOF

      - name: Set Docker image name
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "APP_IMAGE=$IMAGE_NAME:${{ inputs.image_tag }}" >> "$GITHUB_ENV"

      - name: Check runner docker and ghcr
        run: |
          echo "whoami=$(whoami)"
          echo "HOME=$HOME"
          docker version
          docker info
          curl -I --max-time 10 https://ghcr.io/v2/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull production images
        # 使用 compose.prod.yaml 拉取镜像
        run: docker compose --env-file .env.prod -f compose.prod.yaml pull

      - name: Start production containers
        # 使用 compose.prod.yaml 启动容器；up：创建并启动服务；-d：后台运行。
        run: docker compose --env-file .env.prod -f compose.prod.yaml up -d

      - name: Show containers
        # 显示当前 compose 项目的容器状态
        run: docker compose --env-file .env.prod -f compose.prod.yaml ps